import Link from 'next/link';
import type {Metadata} from 'next';
import counts from '@/data/crane-counts.json';
import type {CraneSurvey} from '@/lib/types';
import {discoverCurrentYearSurveys,latestVerifiedSurvey} from '@/lib/sources/craneTrust';
import {estimateCurrentAbundance} from '@/lib/models/currentAbundance';
import HistoricalChart from '@/components/HistoricalChart';
export const revalidate=1800;
export const metadata:Metadata={title:'Nebraska Sandhill Crane Counts: Official Surveys & Current Model',description:'Latest official Crane Trust Sandhill Crane survey, uncertainty, current modeled estimate when defensible, and the 2016–2026 Nebraska migration history.',alternates:{canonical:'/crane-counts-nebraska'}};
const archived=counts as CraneSurvey[];
function merge(a:CraneSurvey[],b:CraneSurvey[]){const m=new Map<string,CraneSurvey>();for(const r of [...a,...b])m.set(`${r.year}-${r.surveyWeek}-${r.count}`,r);return [...m.values()].sort((x,y)=>x.date.localeCompare(y.date));}
export default async function Page(){const now=new Date(),year=now.getUTCFullYear(),live=await discoverCurrentYearSurveys(year),all=merge(archived,live),latest=live.at(-1)??latestVerifiedSurvey(now),model=estimateCurrentAbundance(all,now);return <main id="main" className="shell" style={{padding:'42px 20px 70px'}}><p className="eyebrow">OFFICIAL VS MODELED</p><h1>Nebraska Sandhill Crane counts</h1><p className="lede">The observational anchor is the Crane Trust aerial abundance index. Platte Crane Live never relabels a between-survey estimate as an official or “live” count.</p><section className="panel"><div className="metric-row"><div className="metric"><span className="muted">Latest official survey</span><strong>{latest?latest.count.toLocaleString():'Unavailable'}</strong><div>{latest?.error?`± ${latest.error.toLocaleString()}`:'No published error parsed'}</div><div className="fine">Crane Trust · {latest?.date??'—'}</div></div><div className="metric"><span className="muted">Current modeled estimate</span><strong>{model?`~${model.medianEstimate.toLocaleString()}`:'Withheld'}</strong><div className="fine">{model?`P10–P90 ${model.p10.toLocaleString()}–${model.p90.toLocaleString()}`:'Requires ≥2 current-season surveys and acceptable freshness.'}</div></div><div className="metric"><span className="muted">Model status</span><strong>{model?'Active':'Official data only'}</strong><div className="fine">Modeled values are rounded to 5,000-crane increments.</div></div><div className="metric"><span className="muted">Historical archive</span><strong>{all.length} records</strong><div className="fine">Provenance retained per observation.</div></div></div></section><div style={{marginTop:16}}><HistoricalChart data={all}/></div><section className="panel method" style={{marginTop:16}}><h2>How to read the numbers</h2><p>Aerial survey values are population indices for the Central Platte survey corridor, not exact real-time censuses of every crane in Nebraska. Survey uncertainty and data age matter, especially during fast arrival or departure periods.</p><p><Link href="/">Back to current decision dashboard</Link> · <Link href="/methodology">Methodology</Link></p></section></main>}
