import Link from 'next/link';
import counts from '@/data/crane-counts.json';
import sites from '@/data/viewing-sites.json';
import type {CraneSurvey, WeatherHour} from '@/lib/types';
import {fetchRiverGauges} from '@/lib/sources/usgs';
import {fetchActiveAlerts,fetchCorridorWeather} from '@/lib/sources/nws';
import {discoverCurrentYearDistribution,discoverCurrentYearSurveys,latestVerifiedSurvey} from '@/lib/sources/craneTrust';
import {seasonMode} from '@/lib/models/climatology';
import {dailyHistoricalClimatology} from '@/lib/models/dailyClimatology';
import {fetchDroughtStates} from '@/lib/sources/droughtMonitor';
import {preseasonTimingPressure} from '@/lib/models/seasonTiming';
import {rankViewingSites,type ViewingSite} from '@/lib/models/siteRanking';
import {fetchDailyTemperatureNormals,temperatureDepartureF} from '@/lib/sources/climateNormals';
import {classifyPulse,confidenceFromSurvey,riverHabitat,movementPotential,roostOutlook,safetyOverride} from '@/lib/models/core';
import {estimateCurrentAbundance} from '@/lib/models/currentAbundance';
import {solarTimes} from '@/lib/astronomy/solar';
import {ageLabel,freshness} from '@/lib/freshness';
import HistoricalChart from '@/components/HistoricalChart';
import CorridorMap from '@/components/CorridorMap';
import CameraCard from '@/components/CameraCard';

const archived=counts as CraneSurvey[]; export const revalidate=900;
function fmt(n:number|null){return n==null?'Unavailable':Math.round(n).toLocaleString()}
function time(iso:string|null){return iso?new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',hour:'numeric',minute:'2-digit'}).format(new Date(iso)):'—'}
function shiftMinutes(iso:string|null,minutes:number){if(!iso)return null; return new Date(new Date(iso).getTime()+minutes*60000).toISOString()}
function closestHour(hours:WeatherHour[]|undefined, iso:string|null){if(!hours?.length||!iso)return hours?.[0]; const t=new Date(iso).getTime(); return [...hours].sort((a,b)=>Math.abs(new Date(a.startTime).getTime()-t)-Math.abs(new Date(b.startTime).getTime()-t))[0];}
function weatherScore(h:WeatherHour|undefined){if(!h)return 8; let score=20; score-=Math.min(12,(h.precipProbability??0)*.12); if(h.windSpeedMph>25)score-=Math.min(6,(h.windSpeedMph-25)*.35); if((h.skyCover??50)>90)score-=1; return Math.max(0,Math.min(20,Math.round(score)));}
function mergeSurveys(base:CraneSurvey[], live:CraneSurvey[]){const m=new Map<string,CraneSurvey>(); for(const r of [...base,...live]){const key=`${r.year}-${r.surveyWeek}-${r.count}`; const old=m.get(key); if(!old||r.datePrecision==='exact')m.set(key,r);} return [...m.values()].sort((a,b)=>a.date.localeCompare(b.date));}
function confidencePoints(c:string){return c==='High'?10:c==='Moderate'?8:c==='Low'?5:3}

export default async function Home(){
  const now=new Date(); const year=now.getUTCFullYear(); const solar=solarTimes(now);
  const [gauges,weather,alerts,discovered,drought,distribution,normals]=await Promise.all([fetchRiverGauges(),fetchCorridorWeather(),fetchActiveAlerts(),discoverCurrentYearSurveys(year),fetchDroughtStates(),discoverCurrentYearDistribution(year),fetchDailyTemperatureNormals(now)]);
  const all=mergeSurveys(archived,discovered); const current=all.filter(r=>r.year===year).sort((a,b)=>a.date.localeCompare(b.date));
  const latestCurrent=current.at(-1)??null; const latest=latestCurrent??latestVerifiedSurvey(now); const hasCurrent=!!latestCurrent&&now.getUTCMonth()<=4; const mode=seasonMode(now,hasCurrent);
  const river=riverHabitat(gauges); const gibbon=weather.find(w=>w.key==='gibbon'); const evening=closestHour(gibbon?.hours,solar.sunset); const warmest=(gibbon?.hours??[]).slice(0,18).reduce<WeatherHour|undefined>((best,h)=>!best||h.temperature>best.temperature?h:best,undefined); const progress=Math.max(0,Math.min(1,(now.getTime()-Date.UTC(year,1,15))/(Date.UTC(year,3,10)-Date.UTC(year,1,15)))); const move=movementPotential(warmest,progress); const tempDeparture=temperatureDepartureF(gibbon?.hours??[],normals,now); const abundance=mode==='SPRING_LIVE'?estimateCurrentAbundance(all,now,{movementScore:move.score,tempDepartureF:tempDeparture?.departureF??null,precipProbability:warmest?.precipProbability??null,seasonProgress:progress}):null; const safety=safetyOverride(alerts); const dailyClim=dailyHistoricalClimatology(all); const histPeak=Math.max(...dailyClim.map(x=>x.median));
  const nextYear=mode==='OFF_SEASON'?year+1:year; const typicalArrival=new Date(Date.UTC(nextYear,1,15)); const days=Math.max(0,Math.ceil((typicalArrival.getTime()-now.getTime())/86400000)); const timing=preseasonTimingPressure(now,current,all,drought);
  const pulse=abundance?classifyPulse(abundance.change48hPct):null; const conf=abundance?confidenceFromSurvey(abundance.dataAgeHours,[gibbon?.hours?.length?1:0,gauges.filter(g=>g.discharge!=null).length>=2?1:0].reduce((a,b)=>a+b,0)):'Historical guidance';
  const abundancePoints=abundance?Math.round(Math.min(45,45*abundance.medianEstimate/Math.max(1,histPeak))):0; const weatherPoints=weatherScore(evening); const timingPoints=mode==='SPRING_LIVE'?Math.max(5,10-Math.min(5,Math.abs(abundance?.change48hPct??0)/10)):0; const outlook=mode==='SPRING_LIVE'?roostOutlook(abundancePoints,weatherPoints,river.score,timingPoints,confidencePoints(conf),safety.unsafe):null;
  const surveyFresh=latest?freshness(`${latest.date}T12:00:00Z`,now,'survey'):'UNAVAILABLE'; const arriveStart=shiftMinutes(solar.sunset,-60); const arriveEnd=shiftMinutes(solar.sunset,-45); const activityEnd=shiftMinutes(solar.sunset,35); const siteRows=sites as ViewingSite[]; const duskRank=rankViewingSites(siteRows,'dusk',weather,gauges,distribution,river.score,solar.sunset); const dawnRank=rankViewingSites(siteRows,'dawn',weather,gauges,distribution,river.score,solar.sunrise); const bestDusk=duskRank[0]??null; const bestDawn=dawnRank[0]??null;

  const schema={"@context":"https://schema.org","@graph":[{"@type":"WebApplication","name":"Platte Crane Live","applicationCategory":"TravelApplication","operatingSystem":"Web","description":"Nebraska Sandhill Crane migration decision intelligence combining official surveys, historical timing, weather and Platte River conditions.","url":process.env.NEXT_PUBLIC_SITE_URL||"https://platte-crane-live-izworski-gmailcoms-projects.vercel.app"},{"@type":"Dataset","name":"Platte Crane Live Sandhill Crane Survey Archive","description":"Provenance-bearing Crane Trust Central Platte River Valley aerial survey observations used for historical migration analysis and model validation.","creator":{"@type":"Organization","name":"Crane Trust"},"temporalCoverage":"2016/2026","isBasedOn":"https://www.cranetrust.org/crane-counts/"},{"@type":"Place","name":"Central Platte River Valley crane viewing corridor","address":{"@type":"PostalAddress","addressRegion":"NE","addressCountry":"US"}}]};
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
    <header className="site-head shell"><div className="brand">PLATTE CRANE LIVE<small>Nebraska Sandhill Crane Migration Intelligence</small></div><nav className="nav" aria-label="Main"><a href="#history">Migration history</a><a href="#map">Viewing map</a><a href="#river">River</a><a href="#method">Methodology</a></nav></header>
    <section className="hero"><div className="shell hero-inner"><p className="eyebrow">NEBRASKA · CENTRAL PLATTE RIVER VALLEY</p><h1>Platte Crane Live</h1><h2>{mode==='OFF_SEASON'?`${nextYear} Migration Watch`:mode==='WINTER_WATCH'?'Winter Crane Watch':'Spring Live Mode'}</h2><p>Measured surveys, historical migration shape, river conditions and weather — combined without pretending a modeled estimate is a live bird count.</p></div></section>
    <div className="shell watch-strip"><div className="watch"><div><p className="eyebrow">CURRENT MODE</p><div className="big">{mode==='OFF_SEASON'?`${nextYear} migration watch`:mode.replaceAll('_',' ')}</div><div className="muted">{mode==='OFF_SEASON'?`${days} days until typical mid-February arrival window`:'Current-season data mode'}</div></div><div><span className="muted">Typical arrivals</span><div className="big">Mid-February</div><div className="fine">Variable year to year</div></div><div><span className="muted">Historic peak</span><div className="big">Mid-to-late March</div><div className="fine">Highly variable across years</div></div><div><span className="muted">Latest official survey</span><div className="big">{latest?`${fmt(latest.count)}${latest.error?` ± ${fmt(latest.error)}`:''}`:'Unavailable'}</div><div className="fine">{latest?`Crane Trust · ${latest.date}`:'No verified survey'}</div><span className={`fresh ${surveyFresh}`}>{latest?ageLabel(`${latest.date}T12:00:00Z`,now):'Unavailable'}</span></div></div></div>
    <main id="main" className="shell"><div className="grid">
      <section className={`panel span12 status-banner ${safety.unsafe?'unsafe':''}`}><p className="eyebrow">DECISION FIRST</p><h2>{safety.unsafe?'Viewing conditions unsafe':mode==='OFF_SEASON'?`${nextYear} live abundance modeling is intentionally off`:abundance&&outlook?`${outlook.label} · ${outlook.total}/100 tonight`:'Current migration intelligence'}</h2><p>{safety.unsafe?`${safety.reason} is active in the corridor. Safety overrides viewing scores.`:mode==='OFF_SEASON'?'It is off-season, so no fake crane probability is shown. Use the historical curve, public viewing map, river context and live weather while the system watches for the next verified Crane Trust observation.':abundance?`Modeled abundance is ${fmt(abundance.medianEstimate)} with a plausible p10–p90 range of ${fmt(abundance.p10)}–${fmt(abundance.p90)}. This is a model estimate anchored to official surveys, not a live count.`:'At least two defensible current-season official observations are required before the between-survey abundance model activates.'}</p></section>

      <section className="panel span12"><div className="metric-row"><div className="metric"><p className="eyebrow">MODELED CRANES</p><strong>{abundance?`~${fmt(abundance.medianEstimate)}`:mode==='SPRING_LIVE'?'Awaiting ≥2 surveys':'Not published off-season'}</strong><div className="fine">{abundance?`Plausible p10–p90: ${fmt(abundance.p10)}–${fmt(abundance.p90)}`:'Never labeled a live count.'}</div></div><div className="metric"><p className="eyebrow">MIGRATION PULSE</p><strong>{pulse??(mode==='SPRING_LIVE'?'AWAITING DATA':'WATCHING')}</strong><div className="fine">{abundance?`${abundance.change48hPct>0?'+':''}${abundance.change48hPct}% modeled 48-hour change`:'Abundance change, not wind alone.'}</div></div><div className="metric"><p className="eyebrow">PEAK VIEWING PROBABILITY</p><strong>{abundance?`${abundance.peakProbability}%`:'—'}</strong><div className="fine">Probability current abundance is near the historical peak-quality threshold.</div></div><div className="metric"><p className="eyebrow">MOVEMENT POTENTIAL</p><strong>{gibbon?.hours?.length?`${move.score}/100`:'Unavailable'}</strong><div className="fine">Flight-weather signal; late-season movement can accelerate departures.</div></div></div></section>

      {abundance&&outlook&&<section className="panel span12"><div className="section-head"><div><p className="eyebrow">TONIGHT</p><h2>{outlook.label} · {outlook.total}/100</h2><p>Recommended general public-site arrival {time(arriveStart)}–{time(arriveEnd)}. Best activity is often around sunset through roughly {time(activityEnd)}; bird behavior varies.</p></div><div className="big">Confidence: {conf}</div></div><div className="why-grid"><div><span>Abundance</span><strong>{outlook.parts.abundance}/45</strong></div><div><span>Weather</span><strong>{outlook.parts.weather}/20</strong></div><div><span>River</span><strong>{outlook.parts.river}/15</strong></div><div><span>Timing</span><strong>{outlook.parts.timing}/10</strong></div><div><span>Confidence</span><strong>{outlook.parts.confidence}/10</strong></div></div><p className="fine">Why: {abundance.primaryDrivers.join(' ')} {river.reason}</p></section>}

      <section className="panel span4"><p className="eyebrow">SEASON TIMING</p><h2>{timing.label}</h2><p>{timing.reason}</p><div className="fine">Confidence: {timing.confidence}{timing.active?'':' · dormant signal'}</div>{tempDeparture&&<><hr/><div className="big">{tempDeparture.departureF>0?'+':''}{tempDeparture.departureF}°F</div><div className="muted">Forecast daily max vs normal</div><div className="fine">{tempDeparture.forecastMaxF}°F forecast · {tempDeparture.normalMaxF}°F normal · {tempDeparture.basis}</div></>}</section>
      <section className="panel span8"><p className="eyebrow">LATEST DISTRIBUTION INTELLIGENCE</p><h2>{distribution?'Crane Trust corridor narrative':'No current distribution narrative'}</h2><p>{distribution?.text??'The tool will not infer a heat map or site concentration from vague or unavailable prose.'}</p>{distribution&&<p className="fine">Crane Trust · {distribution.date} · <a href={distribution.sourceUrl??'#'} target="_blank" rel="noreferrer">source ↗</a></p>}<div className="fine">Drought timing inputs: {drought.map(d=>`${d.state} ${d.d2==null?'unavailable':`D2+ ${Math.round(d.d2)}%`}`).join(' · ')}</div></section>
      <div id="history" className="span12"><HistoricalChart data={all}/></div><div id="map" className="span8"><CorridorMap/></div><CameraCard/>
      <section id="river" className="panel span12"><div className="section-head"><div><p className="eyebrow">USGS NEAR REAL TIME</p><h2>Platte roost-habitat proxy</h2><p>{river.reason}</p></div><div className="big">{river.label}</div></div><div className="metric-row">{gauges.map(g=><div className="metric" key={g.site}><span className="muted">{g.name}</span><strong>{g.discharge==null?'Unavailable':`${Math.round(g.discharge).toLocaleString()} cfs`}</strong><div>{g.gageHeight==null?'':`${g.gageHeight.toFixed(2)} ft stage`}</div><span className={`fresh ${g.freshness}`}>{g.observedAt?ageLabel(g.observedAt):'USGS unavailable'}</span></div>)}</div></section>
      <section className="panel span12"><p className="eyebrow">WHERE SHOULD I GO?</p><h2>{mode==='SPRING_LIVE'&&distribution?'Current public-site ranking':'Public viewing planning'}</h2><p className="muted">Private and sensitive roost locations are excluded. Rankings combine public access, viewing mode, local weather, corridor river conditions and only coarse official distribution language. They never guarantee cranes at a site.</p>{mode==='SPRING_LIVE'&&<div className="recommend-grid"><article className="recommend-card"><span className="tag">{bestDusk?.distributionSupported?'BEST TONIGHT':'BEST FIT TONIGHT'}</span><h3>{bestDusk?.name??'Unavailable'}</h3><div className="big">{bestDusk?.score??'—'}/100</div><p>{bestDusk?.why?.join(' ')}</p><div className="fine">Arrive roughly {time(arriveStart)}–{time(arriveEnd)}, subject to current site rules.</div></article><article className="recommend-card"><span className="tag">{bestDawn?.distributionSupported?'BEST TOMORROW MORNING':'BEST FIT MORNING'}</span><h3>{bestDawn?.name??'Unavailable'}</h3><div className="big">{bestDawn?.score??'—'}/100</div><p>{bestDawn?.why?.join(' ')}</p><div className="fine">General dawn planning: arrive 30–45 minutes before sunrise, subject to site rules.</div></article></div>}<div className="site-list">{siteRows.map(s=><article className="site-card" key={s.id}><span className="tag">{s.publicStatus.includes('Public')?'Public':'Controlled access'}</span><h3>{s.name}</h3><p>{s.bestTime.join(' · ')}</p><p className="fine"><b>Access:</b> {s.permit}</p><p className="fine"><b>Parking:</b> {s.parking}</p><p className="fine"><b>Accessibility:</b> {s.accessibility}</p><a className="source-link" href={s.source} target="_blank" rel="noreferrer">Source / current details ↗</a></article>)}</div></section>
      <section className="panel span8"><p className="eyebrow">WILDLIFE FIRST</p><h2>Observe without moving the birds</h2><p>Use designated viewing sites, respect private property, stay with your vehicle at roadside viewing areas, keep distance from feeding flocks and river roosts, and never stop in an active traffic lane. Sensitive roost coordinates are not published here.</p></section>
      <section className="panel span4"><p className="eyebrow">SUN · CENTRAL TIME</p><h2>Viewing light</h2><div><b>Sunrise</b> {time(solar.sunrise)}</div><div><b>Sunset</b> {time(solar.sunset)}</div><div><b>Civil dusk</b> {time(solar.civilDusk)}</div><p className="fine">During spring, general public-site planning guidance is typically arrival 45–60 minutes before sunset or 30–45 minutes before sunrise, subject to site rules.</p></section>
      <section className="panel span12"><p className="eyebrow">PLAN THE TRIP</p><h2>Focused Nebraska crane tools</h2><div className="site-list"><article className="site-card"><h3>Current crane counts</h3><p>Official Crane Trust surveys versus the between-survey model, with uncertainty and history.</p><Link href="/crane-counts-nebraska">Open crane counts →</Link></article><article className="site-card"><h3>Best time to go</h3><p>Historical peak-quality dates plus dawn and dusk planning windows.</p><Link href="/best-time-to-see-sandhill-cranes-nebraska">Open timing guide →</Link></article><article className="site-card"><h3>Public viewing map</h3><p>Verified public and controlled-access locations without sensitive roost coordinates.</p><Link href="/platte-river-crane-viewing-map">Open viewing map →</Link></article></div></section>
      <div className="span12 ad-slot" aria-label="Reserved advertising area">Reserved ad area — intentionally below primary decision content</div>
      <section id="method" className="panel span12 method"><p className="eyebrow">METHODOLOGY</p><h2>Measured first. Modeled second.</h2><p>Crane Trust aerial surveys are the observational anchor and are presented as an abundance index with uncertainty, not an exact real-time census. Between surveys, the candidate model starts with the backtested official-survey transition ensemble and daily shape-preserving historical climatology. A deliberately bounded operational adjustment can then reflect current movement weather; its contribution is exposed separately because the weather adjustment is not itself an observed crane count. Strong migration weather can mean arrivals early in spring or departures late in spring.</p><p>The historical benchmark excludes the held-out year from its climatology. If the candidate cannot beat the strongest naïve baseline, the site falls back to official surveys plus historical guidance rather than publishing a more complicated model.</p><p><Link href="/methodology">Read full methodology</Link> · <a href="/api/status">Machine-readable source status</a></p></section>
    </div></main><footer className="footer"><div className="shell"><b>PLATTE CRANE LIVE</b><p>Independent decision-support tool. Crane observations remain attributed to Crane Trust; weather to NOAA/NWS; river data to USGS; camera to Audubon/Explore.org.</p></div></footer>
  </>;
}
