'use client';
import {useMemo,useState} from 'react';
import type {CraneSurvey} from '@/lib/types';
import {dailyHistoricalClimatology,interpolatedYearTrajectory} from '@/lib/models/dailyClimatology';
const W=760,H=320,P=44,MAX=800000;
export default function HistoricalChart({data}:{data:CraneSurvey[]}){
  const [years,setYears]=useState<number[]>([2026,2025]);
  const daily=useMemo(()=>dailyHistoricalClimatology(data),[data]);
  const grouped=useMemo(()=>{const m=new Map<number,CraneSurvey[]>();for(const d of data){const a=m.get(d.year)??[];a.push(d);m.set(d.year,a);}return m;},[data]);
  const trajectories=useMemo(()=>new Map(years.map(y=>[y,interpolatedYearTrajectory(data,y)])),[data,years]);
  const x=(i:number)=>P+i*(W-2*P)/Math.max(1,daily.length-1); const y=(v:number)=>H-P-Math.min(MAX,Math.max(0,v))/MAX*(H-2*P);
  const path=(vals:{dayIndex:number,count:number}[])=>vals.map((d,i)=>`${i?'L':'M'}${x(d.dayIndex)},${y(d.count)}`).join(' ');
  const band=[...daily.map(d=>`${x(d.dayIndex)},${y(d.p20)}`),...daily.slice().reverse().map(d=>`${x(d.dayIndex)},${y(d.p80)}`)].join(' ');
  const dateIndex=(date:string)=>{const d=new Date(`${date}T12:00:00Z`);return Math.max(0,Math.min(daily.length-1,Math.round((Date.UTC(2024,d.getUTCMonth(),d.getUTCDate())-Date.UTC(2024,1,1))/86400000)));};
  return <section className="panel chart-panel" aria-labelledby="hist-title"><div className="section-head"><div><p className="eyebrow">2016–2026 OBSERVATIONS + DAILY CLIMATOLOGY</p><h2 id="hist-title">Is this season early, normal, or late?</h2><p>Observed Crane Trust survey points remain discrete. Thin daily curves use shape-preserving interpolation only for comparison and modeling.</p></div><div className="year-toggles">{[2026,2025,2024].map(v=><button key={v} aria-pressed={years.includes(v)} onClick={()=>setYears(s=>s.includes(v)?s.filter(x=>x!==v):[...s,v])}>{v}</button>)}</div></div><div className="chart-wrap"><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Daily historical Sandhill Crane abundance climatology with 20th to 80th percentile band, median, selected interpolated seasons, and actual survey observations.">{[0,200000,400000,600000,800000].map(v=><g key={v}><line x1={P} x2={W-P} y1={y(v)} y2={y(v)} className="chart-grid"/><text x={4} y={y(v)+4}>{v===0?'0':`${v/1000}k`}</text></g>)}<polygon points={band} className="range-band"/><path d={path(daily.map(d=>({dayIndex:d.dayIndex,count:d.median})))} className="median-line"/>{years.map((yr,idx)=><path key={yr} d={path(trajectories.get(yr)??[])} className={`year-line y${idx}`}/>)}{years.flatMap((yr,idx)=>(grouped.get(yr)??[]).filter(d=>d.surveyWeek>0).map(d=><circle key={`${yr}-${d.date}-${d.count}`} cx={x(dateIndex(d.date))} cy={y(d.count)} r="4" className={`dot y${idx}`}><title>{`${yr}: ${d.count.toLocaleString()} · ${d.datePrecision==='exact'?d.date:`${d.date} (${d.datePrecision})`}`}</title></circle>))}<text x={P} y={H-8}>Feb 1</text><text x={x(42)-18} y={H-8}>Mar 15</text><text x={W-P-34} y={H-8}>Apr 20</text></svg></div><p className="chart-note"><b>Shaded band:</b> historical 20th–80th percentile. <b>Dashed line:</b> daily historical median. Survey dots are observations; smooth year lines are interpolated context.</p></section>;
}
