import {test,expect} from '@playwright/test';
const base='/national-tools/platte-crane-live';
test('decision page exposes current mode before secondary tools',async({page})=>{await page.goto(base);await expect(page.getByRole('heading',{name:/Platte Crane Live/i})).toBeVisible();await expect(page.getByText(/migration watch|spring live mode|winter crane watch/i).first()).toBeVisible();await expect(page.getByText(/DECISION FIRST/i)).toBeVisible();});
test('public map explains every point and preserves wildlife protections',async({page})=>{await page.goto(base);await page.getByRole('heading',{name:'Choose a crane-viewing stop'}).scrollIntoViewIfNeeded();await expect(page.getByText(/numbered point is a real public/i)).toBeVisible();await expect(page.getByRole('button',{name:/Open Richard Plautz Crane Viewing Site/i})).toBeVisible();await page.getByRole('button',{name:/Plautz Decks/i}).click();await expect(page.getByRole('heading',{name:'Richard Plautz Crane Viewing Site'})).toBeVisible();await expect(page.getByRole('link',{name:/Directions in Google Maps/i})).toHaveAttribute('href',/google\.com\/maps\/dir/);await expect(page.getByText(/does not publish private feeding locations/i)).toBeVisible();});
test('persona chooser changes which destinations are highlighted',async({page})=>{await page.goto(base);await page.getByRole('button',{name:/Birder \/ photographer/i}).click();await expect(page.getByRole('button',{name:/Rowe Sanctuary/i})).toContainText('Good fit for this trip');});
test('camera links directly to exact Rowe live feed',async({page})=>{await page.goto(base);await page.getByRole('heading',{name:'Rowe Sanctuary live crane camera'}).scrollIntoViewIfNeeded();await expect(page.locator('iframe')).toHaveCount(0);await expect(page.getByRole('link',{name:/Watch the Rowe live camera/i})).toHaveAttribute('href','https://explore.org/livecams/national-audubon-society/crane-camera');});
test('methodology distinguishes observations and model',async({page})=>{await page.goto(`${base}/methodology`);await expect(page.getByRole('heading',{name:'Official survey vs. modeled estimate'})).toBeVisible();});
test('supporting crane counts route has unique decision content',async({page})=>{await page.goto(`${base}/crane-counts-nebraska`);await expect(page.getByRole('heading',{name:'Nebraska Sandhill Crane counts'})).toBeVisible();await expect(page.getByText(/Latest official survey/)).toBeVisible();});
test('mobile has no horizontal overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto(base);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1);});
