import type { CraneSurvey, Confidence, RiverGauge, WeatherHour } from '@/lib/types';
export function median(a:number[]){const x=[...a].sort((a,b)=>a-b); if(!x.length)return 0; const m=Math.floor(x.length/2); return x.length%2?x[m]:(x[m-1]+x[m])/2;}
export function quantile(a:number[],q:number){const x=[...a].sort((a,b)=>a-b); if(!x.length)return 0; const p=(x.length-1)*q,b=Math.floor(p),r=p-b; return x[b+1]===undefined?x[b]:x[b]+r*(x[b+1]-x[b]);}
export function classifyPulse(change:number){return change>12?'SURGING':change>4?'RISING':change>=-4?'HOLDING':change>=-12?'EASING':'DEPARTING RAPIDLY';}
export function southerlyTailwind(speed:number,dirDeg:number){const from=dirDeg*Math.PI/180; return Math.max(0,speed*Math.cos(from-Math.PI));}
export function movementPotential(h:WeatherHour|undefined,seasonProgress=.5){if(!h)return {score:0,label:'Unavailable'}; const tail=southerlyTailwind(h.windSpeedMph,h.windDirectionDeg); let s=30+Math.min(35,tail*3)+Math.max(-10,Math.min(15,(h.temperature-45)*.6))-(h.precipProbability??0)*.25-(h.skyCover??35)*.05; s=Math.round(Math.max(0,Math.min(100,s))); return {score:s,label:s>=80?'Strong':s>=60?'Favorable':s>=40?'Mixed':'Weak',lateSeasonDepartureRisk:seasonProgress>.65&&s>=75};}
export function riverHabitat(g:RiverGauge[]){const flows=g.map(x=>x.discharge).filter((x):x is number=>x!=null&&x>=0); if(flows.length<2)return {score:7,label:'UNCERTAIN',reason:'Too few current gauges are available to characterize the corridor.'}; const med=median(flows); let score=12; if(med<350||med>4500)score=4; else if(med<550||med>3200)score=8; const spread=(Math.max(...flows)-Math.min(...flows))/(med||1); if(spread>1.4)score-=2; return {score:Math.max(0,Math.min(15,score)),label:score>=11?'FAVORABLE':score>=7?'MIXED':'LIMITED',reason:score>=11?'Flows are within a broad range historically compatible with shallow-water roost habitat; discharge is only a proxy for local depth.':'Corridor flows are outside the broad central range or spatially inconsistent; local channel geometry remains important.'};}
export function confidenceFromSurvey(ageHours:number,liveInputs:number):Confidence{if(ageHours<96&&liveInputs>=2)return'High'; if(ageHours<240&&liveInputs>=1)return'Moderate'; if(ageHours<504)return'Low'; return'Historical guidance';}
export function safetyOverride(alerts:{event:string;severity:string}[]){const bad=['Tornado Warning','Severe Thunderstorm Warning','Blizzard Warning','Ice Storm Warning','Flash Flood Warning']; const hit=alerts.find(a=>bad.includes(a.event)); return hit?{unsafe:true,reason:hit.event}:{unsafe:false,reason:null};}
export function roostOutlook(abundanceScore:number,weatherScore:number,riverScore:number,timingScore:number,confidenceScore:number,safety=false){const parts={abundance:Math.min(45,Math.max(0,abundanceScore)),weather:Math.min(20,Math.max(0,weatherScore)),river:Math.min(15,Math.max(0,riverScore)),timing:Math.min(10,Math.max(0,timingScore)),confidence:Math.min(10,Math.max(0,confidenceScore))}; let total=Object.values(parts).reduce((a,b)=>a+b,0); if(safety)total=Math.min(total,29); const label=total>=90?'EXCEPTIONAL':total>=80?'EXCELLENT':total>=70?'VERY GOOD':total>=60?'GOOD':total>=45?'MIXED':total>=30?'MARGINAL':'LOW'; return {total,label,parts};}
export function estimateFromSurveys(all:CraneSurvey[],year:number,week:number,latest:CraneSurvey|null){if(!latest||latest.year!==year)return null; const others=[...new Set(all.filter(r=>r.year!==year&&r.year>=2016).map(r=>r.year))]; const current=all.filter(r=>r.year===year&&r.surveyWeek>0&&r.surveyWeek<=week).sort((a,b)=>a.surveyWeek-b.surveyWeek); if(current.length<2)return null; const prev=current.at(-1)!; const ratios=others.map(y=>{const a=all.find(r=>r.year===y&&r.surveyWeek===week+1)?.count,p=all.find(r=>r.year===y&&r.surveyWeek===week)?.count; return a!=null&&p!=null&&p>0?a/p:null}).filter((x):x is number=>x!=null&&Number.isFinite(x)); if(ratios.length<4)return null; const targetDate=all.filter(r=>r.surveyWeek===week+1&&r.year!==year).map(r=>r.count); const m=median(targetDate), paths:Array<number>=[]; let seed=year*100+week; const rnd=()=>{seed=(seed*1664525+1013904223)>>>0; return seed/4294967296}; for(let i=0;i<2500;i++){const ratio=ratios[Math.floor(rnd()*ratios.length)]; const jitter=.88+rnd()*.24; paths.push(.75*prev.count*ratio*jitter+.25*m*jitter);} return {medianEstimate:Math.round(median(paths)/5000)*5000,p10:Math.round(quantile(paths,.1)/5000)*5000,p25:Math.round(quantile(paths,.25)/5000)*5000,p75:Math.round(quantile(paths,.75)/5000)*5000,p90:Math.round(quantile(paths,.9)/5000)*5000,paths};}
