import type {CraneSurvey} from '@/lib/types';
import {median,quantile} from './core';

export interface DailyClimatologyPoint {dateKey:string; dayIndex:number; median:number; p20:number; p80:number; min:number; max:number; variance:number; peakWindowProbability:number; sampleSize:number;}

const START_MONTH=1, START_DAY=1, END_MONTH=3, END_DAY=20; // Feb 1-Apr 20
function dayIndex(date:string){const d=new Date(`${date}T12:00:00Z`); const start=Date.UTC(d.getUTCFullYear(),START_MONTH,START_DAY); return Math.round((d.getTime()-start)/86400000);}
function anchorDay(row:CraneSurvey){if(row.datePrecision==='exact')return dayIndex(row.date); return 10+(Math.max(1,row.surveyWeek)-1)*7;}
function endIndex(year:number){return Math.round((Date.UTC(year,END_MONTH,END_DAY)-Date.UTC(year,START_MONTH,START_DAY))/86400000);}

function pchipSlopes(xs:number[],ys:number[]){const n=xs.length;if(n<2)return ys.map(()=>0); const h=Array.from({length:n-1},(_,i)=>xs[i+1]-xs[i]); const d=h.map((v,i)=>(ys[i+1]-ys[i])/v); const m=new Array<number>(n).fill(0); m[0]=d[0];m[n-1]=d[n-2]; for(let i=1;i<n-1;i++){if(d[i-1]===0||d[i]===0||Math.sign(d[i-1])!==Math.sign(d[i])){m[i]=0;continue;} const w1=2*h[i]+h[i-1],w2=h[i]+2*h[i-1];m[i]=(w1+w2)/(w1/d[i-1]+w2/d[i]);} return m;}
function pchip(xs:number[],ys:number[],x:number){if(xs.length===0)return 0;if(xs.length===1)return ys[0];if(x<=xs[0])return ys[0];if(x>=xs.at(-1)!)return ys.at(-1)!; const m=pchipSlopes(xs,ys); let i=0;while(i<xs.length-2&&x>xs[i+1])i++; const h=xs[i+1]-xs[i],t=(x-xs[i])/h,t2=t*t,t3=t2*t; const y=(2*t3-3*t2+1)*ys[i]+(t3-2*t2+t)*h*m[i]+(-2*t3+3*t2)*ys[i+1]+(t3-t2)*h*m[i+1]; return Math.max(0,y);}

export function interpolatedYearTrajectory(all:CraneSurvey[],year:number){const rows=all.filter(r=>r.year===year&&r.surveyWeek>0).sort((a,b)=>anchorDay(a)-anchorDay(b)); const xs:number[]=[],ys:number[]=[]; for(const r of rows){const x=anchorDay(r); if(xs.at(-1)===x){ys[ys.length-1]=r.count;}else{xs.push(x);ys.push(r.count);}} const end=endIndex(year); return Array.from({length:end+1},(_,i)=>({dayIndex:i,count:pchip(xs,ys,i),observed:false}));}

export function dailyHistoricalClimatology(all:CraneSurvey[],startYear=2016,endYear=2025):DailyClimatologyPoint[]{const years=Array.from({length:endYear-startYear+1},(_,i)=>startYear+i); const trajectories=new Map(years.map(y=>[y,interpolatedYearTrajectory(all,y)])); const end=endIndex(2024); const peaks=years.map(y=>Math.max(...(trajectories.get(y)??[]).map(p=>p.count))); return Array.from({length:end+1},(_,i)=>{const vals=years.map(y=>trajectories.get(y)?.[i]?.count).filter((v):v is number=>v!=null&&Number.isFinite(v)); const med=median(vals); const variance=vals.reduce((s,v)=>s+(v-med)**2,0)/(vals.length||1); const peakWindowProbability=years.filter((y,j)=>(trajectories.get(y)?.[i]?.count??0)>=.85*(peaks[j]||1)).length/years.length; const d=new Date(Date.UTC(2024,START_MONTH,START_DAY+i)); return {dateKey:`${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`,dayIndex:i,median:med,p20:quantile(vals,.2),p80:quantile(vals,.8),min:Math.min(...vals),max:Math.max(...vals),variance,peakWindowProbability:Math.round(peakWindowProbability*100),sampleSize:vals.length};});}

export function historicalForDate(all:CraneSurvey[],date:Date){const idx=Math.max(0,Math.min(endIndex(date.getUTCFullYear()),Math.round((Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate())-Date.UTC(date.getUTCFullYear(),START_MONTH,START_DAY))/86400000))); return dailyHistoricalClimatology(all)[idx]??null;}

export function timingStatus(all:CraneSurvey[],latest:CraneSurvey|null){if(!latest)return {label:'Unknown',detail:'No current survey available.'}; const target=new Date(`${latest.date}T12:00:00Z`); const h=historicalForDate(all,target); if(!h||h.median<=0)return {label:'Near normal',detail:'Historical comparison is limited this early in the season.'}; const ratio=latest.count/h.median; if(ratio>=1.45)return {label:'Much earlier than normal',detail:`Latest abundance is about ${Math.round((ratio-1)*100)}% above the historical median for this point in the season.`}; if(ratio>=1.18)return {label:'Earlier than normal',detail:`Latest abundance is about ${Math.round((ratio-1)*100)}% above the historical median for this date.`}; if(ratio<=.55)return {label:'Much later than normal',detail:`Latest abundance is well below the historical median for this date; timing may be delayed or the season may already be departing.`}; if(ratio<=.82)return {label:'Later than normal',detail:`Latest abundance is about ${Math.round((1-ratio)*100)}% below the historical median for this date.`}; return {label:'Near normal',detail:'Latest abundance is within the broad historical timing envelope for this date.'};}
