import type {RiverGauge,WeatherHour} from '@/lib/types';
export interface ViewingSite {id:string;name:string;lat:number;lon:number;publicStatus:string;bestTime:string[];permit:string;parking:string;accessibility:string;source:string;address:string;}
export interface DistributionNarrative {text:string;date:string|null;keywords:string[];sourceUrl:string|null;}
function distBoost(site:ViewingSite,keywords:string[]){const hay=(site.name+' '+site.address).toLowerCase(); let b=0; for(const k of keywords){const canonical=k.toLowerCase().replace('highway ','').replace('hwy ',''); if(hay.includes(k.toLowerCase())||hay.includes(canonical))b+=8; if(k.includes('gibbon')&&/gibbon|rowe|plautz/i.test(hay))b+=6; if(k.includes('kearney')&&/kearney|fort kearny/i.test(hay))b+=6; if(k.includes('alda')&&/alda|crane trust/i.test(hay))b+=6;} return Math.min(20,b);}
function closestHour(hours:WeatherHour[]|undefined,targetIso:string|null){if(!hours?.length)return undefined;if(!targetIso)return hours[0];const t=new Date(targetIso).getTime();return [...hours].sort((a,b)=>Math.abs(new Date(a.startTime).getTime()-t)-Math.abs(new Date(b.startTime).getTime()-t))[0];}
function weatherQuality(h:WeatherHour|undefined){if(!h)return 8; let s=20-(h.precipProbability??0)*.12-Math.max(0,h.windSpeedMph-24)*.25; if((h.skyCover??50)>95)s-=1; return Math.max(0,Math.min(20,s));}
function nearestWeather(site:ViewingSite,weather:{key:string;name:string;lat:number;lon:number;hours:WeatherHour[]}[]){return [...weather].sort((a,b)=>(a.lat-site.lat)**2+(a.lon-site.lon)**2-((b.lat-site.lat)**2+(b.lon-site.lon)**2))[0];}
function nearestGauge(site:ViewingSite,gauges:RiverGauge[]){const coords:Record<string,[number,number]>={'06768000':[40.68,-99.54],'06770200':[40.69,-99.08],'06770500':[40.79,-98.47]}; return [...gauges].sort((a,b)=>{const ca=coords[a.site]??[40.72,-98.8],cb=coords[b.site]??[40.72,-98.8];return (ca[0]-site.lat)**2+(ca[1]-site.lon)**2-((cb[0]-site.lat)**2+(cb[1]-site.lon)**2);})[0];}
export function rankViewingSites(sites:ViewingSite[],period:'dawn'|'dusk'|'daytime',weather:{key:string;name:string;lat:number;lon:number;hours:WeatherHour[]}[],gauges:RiverGauge[],distribution:DistributionNarrative|null,riverScore:number,targetIso:string|null){return sites.filter(s=>/public|sanctuary|controlled/i.test(s.publicStatus)).map(site=>{const w=nearestWeather(site,weather),g=nearestGauge(site,gauges); const h=closestHour(w?.hours,targetIso); let score=36; if(site.bestTime.includes(period))score+=18; score+=weatherQuality(h); score+=Math.round(riverScore/15*12); const db=distribution?distBoost(site,distribution.keywords):0; score+=db; if(/controlled|reservation|guided/i.test(site.publicStatus+' '+site.permit))score-=7; score=Math.round(Math.max(0,Math.min(100,score))); const why=[site.bestTime.includes(period)?`Site guidance supports ${period} viewing.`:`This is not primarily a ${period} site.`,h?`${w.name} contributes ${Math.round(weatherQuality(h))}/20 for viewing weather.`:'Local weather unavailable; ranking confidence is reduced.',db>0?'The latest Crane Trust distribution narrative mentions this part of the corridor.':'No site-specific crane concentration is inferred without official distribution evidence.',g?.discharge!=null?`Nearest corridor gauge: ${g.name} ${Math.round(g.discharge).toLocaleString()} cfs.`:'Nearest gauge unavailable.']; return {...site,score,nearestGauge:g??null,weatherPoint:w?.name??null,why,distributionSupported:db>0};}).sort((a,b)=>b.score-a.score);}
