import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const craneRows=JSON.parse(fs.readFileSync(path.join(ROOT,'data','crane-counts.json'),'utf8')).filter(r=>r.year>=2016&&r.year<=2025&&r.surveyWeek>=1&&r.surveyWeek<=9);
const weatherPath=path.join(ROOT,'data','historical-weather-era5.json');
if(!fs.existsSync(weatherPath))throw new Error('Missing data/historical-weather-era5.json. Run npm run weather:fetch first.');
const weather=JSON.parse(fs.readFileSync(weatherPath,'utf8'));
const med=a=>{const x=[...a].sort((p,q)=>p-q);if(!x.length)return 0;return x.length%2?x[(x.length-1)/2]:(x[x.length/2-1]+x[x.length/2])/2};
const quantile=(a,p)=>{const x=[...a].sort((m,n)=>m-n);if(!x.length)return 0;const z=(x.length-1)*p,b=Math.floor(z),r=z-b;return x[b+1]===undefined?x[b]:x[b]+r*(x[b+1]-x[b])};
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const years=[...new Set(craneRows.map(r=>r.year))].sort();const by=(y,w)=>craneRows.find(r=>r.year===y&&r.surveyWeek===w);
const byWeatherDate=new Map();for(const r of weather.rows)byWeatherDate.set(`${r.date}|${r.location}`,r);const locations=weather.locations.map(x=>x.key);
function dateRangeExclusiveInclusive(start,end){const out=[],d=new Date(`${start}T12:00:00Z`),e=new Date(`${end}T12:00:00Z`);for(d.setUTCDate(d.getUTCDate()+1);d<=e;d.setUTCDate(d.getUTCDate()+1))out.push(d.toISOString().slice(0,10));return out;}
function southComponent(speed,dir){if(!Number.isFinite(speed)||!Number.isFinite(dir))return null;return Math.max(0,speed*Math.cos((dir-180)*Math.PI/180));}
function intervalFeatures(year,week){const prev=by(year,week-1),cur=by(year,week);if(!prev||!cur)return null;const dates=dateRangeExclusiveInclusive(prev.date,cur.date),daily=[];for(const date of dates){const locRows=locations.map(loc=>byWeatherDate.get(`${date}|${loc}`)).filter(Boolean);if(!locRows.length)continue;const vals=key=>locRows.map(r=>r[key]).filter(Number.isFinite);const south=locRows.map(r=>southComponent(r.windSpeedMeanMph,r.windDirectionDominantDeg)).filter(Number.isFinite);daily.push({temp:mean(vals('temperatureMeanF')),precip:mean(vals('precipitationIn')),precipHours:mean(vals('precipitationHours')),cloud:mean(vals('cloudCoverMeanPct')),south:mean(south),sunshine:mean(vals('sunshineDurationSeconds'))/3600});}if(daily.length<Math.max(2,Math.floor(dates.length*.6)))return null;return{year,week,start:prev.date,end:cur.date,days:daily.length,datePrecision:cur.datePrecision,temp:mean(daily.map(x=>x.temp)),south:mean(daily.map(x=>x.south)),precip:mean(daily.map(x=>x.precip)),precipHours:mean(daily.map(x=>x.precipHours)),cloud:mean(daily.map(x=>x.cloud)),sunshine:mean(daily.map(x=>x.sunshine))};}
const intervals=[];for(const y of years)for(let w=2;w<=9;w++){const f=intervalFeatures(y,w);if(f)intervals.push(f);}const featureBy=(y,w)=>intervals.find(x=>x.year===y&&x.week===w);
function baseCandidate(targetYear,week,trainingYears){const prev=by(targetYear,week-1)?.count;if(prev==null)return null;const dateVals=trainingYears.map(y=>by(y,week)?.count).filter(Number.isFinite);const ratios=trainingYears.map(y=>{const a=by(y,week)?.count,p=by(y,week-1)?.count;return a!=null&&p>0?a/p:null}).filter(Number.isFinite);if(dateVals.length<3||ratios.length<3)return null;return .75*prev*med(ratios)+.25*med(dateVals);}
function robustZ(value,vals){if(!Number.isFinite(value)||vals.length<3)return 0;const m=med(vals),abs=vals.map(x=>Math.abs(x-m)),mad=med(abs);const scale=mad>1e-6?1.4826*mad:Math.max(1e-6,Math.sqrt(mean(vals.map(x=>(x-m)**2))));return clamp((value-m)/scale,-3,3);}
function peakWeek(trainingYears){const peaks=trainingYears.map(y=>{const rs=craneRows.filter(r=>r.year===y);if(!rs.length)return null;return rs.reduce((a,b)=>b.count>a.count?b:a).surveyWeek;}).filter(Number.isFinite);return Math.round(med(peaks));}
function movementIndex(feat,week,trainingYears){const same=trainingYears.map(y=>featureBy(y,week)).filter(Boolean);if(!feat||same.length<3)return 0;const zTemp=robustZ(feat.temp,same.map(x=>x.temp)),zSouth=robustZ(feat.south,same.map(x=>x.south)),zPrecip=robustZ(feat.precip,same.map(x=>x.precip)),zSun=robustZ(feat.sunshine,same.map(x=>x.sunshine)),zCloud=robustZ(feat.cloud,same.map(x=>x.cloud));const opportunity=.35*zTemp+.45*zSouth-.15*zPrecip+.10*zSun-.05*zCloud;const phase=week<=peakWeek(trainingYears)?1:-1;return clamp(phase*opportunity,-3,3);}
function fitWeatherBeta(trainingYears,targetYear){const xy=[];for(const y of trainingYears){const nested=trainingYears.filter(t=>t!==y);for(let w=2;w<=9;w++){const actual=by(y,w)?.count,base=baseCandidate(y,w,nested),f=featureBy(y,w);if(actual==null||base==null||base<=0||!f)continue;const x=movementIndex(f,w,nested),ylog=Math.log((actual+5000)/(base+5000));if(Number.isFinite(x)&&Number.isFinite(ylog))xy.push([x,ylog]);}}const lambda=4,num=xy.reduce((s,[x,y])=>s+x*y,0),den=xy.reduce((s,[x])=>s+x*x,0)+lambda;return{beta:clamp(num/den,-.35,.35),n:xy.length,targetYear};}
function weatherCandidate(targetYear,week,trainingYears){const base=baseCandidate(targetYear,week,trainingYears),feat=featureBy(targetYear,week);if(base==null||!feat)return null;const fit=fitWeatherBeta(trainingYears,targetYear),x=movementIndex(feat,week,trainingYears),multiplier=clamp(Math.exp(fit.beta*x),.75,1.25);return{base,adjusted:base*multiplier,multiplier,index:x,beta:fit.beta,fitN:fit.n,features:feat};}
const out=[];for(const year of years){const others=years.filter(y=>y!==year);for(let week=2;week<=9;week++){const actual=by(year,week)?.count,prev=by(year,week-1)?.count,wc=weatherCandidate(year,week,others);if(actual==null||prev==null||!wc)continue;const dateVals=others.map(y=>by(y,week)?.count).filter(Number.isFinite),baselineA=med(dateVals),baselineB=prev,calibrationErrors=[];for(const calYear of others){const nested=others.filter(y=>y!==calYear),p=weatherCandidate(calYear,week,nested),act=by(calYear,week)?.count;if(p&&act!=null)calibrationErrors.push(Math.abs(p.adjusted-act));}const radius=calibrationErrors.length?quantile(calibrationErrors,.9):150000,actualPeak=Math.max(...craneRows.filter(r=>r.year===year).map(r=>r.count)),predictedPeak=med(others.map(y=>Math.max(...craneRows.filter(r=>r.year===y).map(r=>r.count))));out.push({year,week,actual,prev,baselineA,baselineB,candidate:wc.base,weatherCandidate:wc.adjusted,multiplier:wc.multiplier,index:wc.index,beta:wc.beta,p10:Math.max(0,wc.adjusted-radius),p90:wc.adjusted+radius,actualPeak,predictedPeak,datePrecision:wc.features.datePrecision});}}
const dirClass=(v,prev)=>{const p=(v/Math.max(prev,1)-1)*100;return p>4?'rising':p<-4?'falling':'holding'};
function metric(key,rows=out){const errs=rows.map(r=>Math.abs(r[key]-r.actual)),pct=rows.filter(r=>r.actual>0).map(r=>Math.abs(r[key]-r.actual)/r.actual*100);return{medianAbsoluteError:med(errs),meanAbsoluteError:mean(errs),MAPE:mean(pct),sMAPE:mean(rows.map(r=>2*Math.abs(r[key]-r.actual)/(Math.abs(r.actual)+Math.abs(r[key])+1e-9)))*100,medianLogError:med(rows.map(r=>Math.abs(Math.log1p(r[key])-Math.log1p(r.actual)))),directionalAccuracyPct:rows.filter(r=>dirClass(r[key],r.prev)===dirClass(r.actual,r.prev)).length/rows.length*100,peakClassificationAccuracyPct:rows.filter(r=>(r[key]>=.85*r.predictedPeak)===(r.actual>=.85*r.actualPeak)).length/rows.length*100};}
const base=metric('candidate'),wx=metric('weatherCandidate'),coverage=out.filter(r=>r.actual>=r.p10&&r.actual<=r.p90).length/out.length*100,exact=out.filter(r=>r.datePrecision==='exact');
const report={n:out.length,historicalWeather:{source:weather.source,upstreamDataset:weather.upstreamDataset,retrievedAt:weather.retrievedAt,locations:weather.locations.map(x=>x.key)},baselineCandidate:base,weatherCandidate:{...wx,p10p90CoveragePct:coverage},medianErrorImprovementVsBasePct:(1-wx.medianAbsoluteError/base.medianAbsoluteError)*100,exactDateSubset:exact.length?{n:exact.length,baselineCandidate:metric('candidate',exact),weatherCandidate:metric('weatherCandidate',exact)}:null,betaMedian:med(out.map(r=>r.beta)),betaRange:[Math.min(...out.map(r=>r.beta)),Math.max(...out.map(r=>r.beta))],multiplierRange:[Math.min(...out.map(r=>r.multiplier)),Math.max(...out.map(r=>r.multiplier))],accepted:wx.medianAbsoluteError<base.medianAbsoluteError&&coverage>=80,acceptanceRule:'Weather enters operational abundance only if leave-one-year-out median absolute error improves over the existing candidate and p10-p90 coverage remains at least 80%.',method:'For each held-out year, weather is standardized against the same survey transition in non-held-out years. A fixed movement-opportunity index combines warmth, southerly wind, precipitation, sunshine and cloud; its sign flips after the training-set median peak week. A single ridge-regularized beta is fit only on nested non-held-out predictions, and the resulting abundance multiplier is bounded to 0.75-1.25.'};
console.log(JSON.stringify(report,null,2));fs.mkdirSync(path.join(ROOT,'artifacts'),{recursive:true});fs.writeFileSync(path.join(ROOT,'artifacts','weather-model-benchmark.json'),JSON.stringify(report,null,2)+'\n');if(process.env.WEATHER_GATE==='1'&&!report.accepted)process.exitCode=2;
