import fs from 'node:fs';
const rows=JSON.parse(fs.readFileSync(new URL('../data/crane-counts.json',import.meta.url),'utf8')).filter(r=>r.year>=2016&&r.year<=2025&&r.surveyWeek>=1&&r.surveyWeek<=9);
const med=a=>{a=[...a].sort((x,y)=>x-y);return a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2};
const q=(a,p)=>{a=[...a].sort((x,y)=>x-y);const x=(a.length-1)*p,b=Math.floor(x),r=x-b;return a[b+1]===undefined?a[b]:a[b]+r*(a[b+1]-a[b])};
const years=[...new Set(rows.map(r=>r.year))]; const by=(y,w)=>rows.find(r=>r.year===y&&r.surveyWeek===w)?.count;
function candidateFor(targetYear,week,trainingYears){const prev=by(targetYear,week-1);if(prev==null)return null;const dateVals=trainingYears.map(y=>by(y,week)).filter(Number.isFinite);const ratios=trainingYears.map(y=>{const a=by(y,week),p=by(y,week-1);return a!=null&&p>0?a/p:null}).filter(Number.isFinite);if(dateVals.length<3||ratios.length<3)return null;const baselineA=med(dateVals);return .75*prev*med(ratios)+.25*baselineA;}
const out=[];
for(const year of years){for(let week=2;week<=9;week++){const actual=by(year,week),prev=by(year,week-1);if(actual==null||prev==null)continue;const others=years.filter(y=>y!==year);const dateVals=others.map(y=>by(y,week)).filter(Number.isFinite);const ratios=others.map(y=>{const a=by(y,week),p=by(y,week-1);return a!=null&&p>0?a/p:null}).filter(Number.isFinite);if(dateVals.length<4||ratios.length<4)continue;const baselineA=med(dateVals),baselineB=prev,candidate=.75*prev*med(ratios)+.25*baselineA;
  const calibrationErrors=[]; for(const calYear of others){const pred=candidateFor(calYear,week,others.filter(y=>y!==calYear));const act=by(calYear,week);if(pred!=null&&act!=null)calibrationErrors.push(Math.abs(pred-act));} const radius=calibrationErrors.length?q(calibrationErrors,.9):150000;
  const actualPeak=Math.max(...rows.filter(r=>r.year===year).map(r=>r.count));const predictedPeak=med(others.map(y=>Math.max(...rows.filter(r=>r.year===y).map(r=>r.count))));
  out.push({year,week,actual,prev,baselineA,baselineB,candidate,p10:Math.max(0,candidate-radius),p90:candidate+radius,actualPeak,predictedPeak});}}
const dirClass=(v,prev)=>{const p=(v/Math.max(prev,1)-1)*100;return p>4?'rising':p<-4?'falling':'holding'};
const metric=(key)=>{const errs=out.map(r=>Math.abs(r[key]-r.actual));const pct=out.filter(r=>r.actual>0).map(r=>Math.abs(r[key]-r.actual)/r.actual*100);return {medianAbsoluteError:med(errs),meanAbsoluteError:errs.reduce((a,b)=>a+b,0)/errs.length,MAPE:pct.reduce((a,b)=>a+b,0)/pct.length,sMAPE:out.reduce((s,r)=>s+2*Math.abs(r[key]-r.actual)/(Math.abs(r.actual)+Math.abs(r[key])+1e-9),0)/out.length*100,medianLogError:med(out.map(r=>Math.abs(Math.log1p(r[key])-Math.log1p(r.actual)))),directionalAccuracyPct:out.filter(r=>dirClass(r[key],r.prev)===dirClass(r.actual,r.prev)).length/out.length*100,peakClassificationAccuracyPct:out.filter(r=>(r[key]>=.85*r.predictedPeak)===(r.actual>=.85*r.actualPeak)).length/out.length*100};};
const a=metric('baselineA'),b=metric('baselineB'),c=metric('candidate');const strongest=Math.min(a.medianAbsoluteError,b.medianAbsoluteError);const coverage=out.filter(r=>r.actual>=r.p10&&r.actual<=r.p90).length/out.length*100;
const report={n:out.length,baselineA:a,baselineB:b,candidate:{...c,p10p90CoveragePct:coverage},medianErrorImprovementPct:(1-c.medianAbsoluteError/strongest)*100,method:'Leave-one-year-out. Candidate = 75% prior official count × median transition ratio from non-held-out years + 25% calendar-date median. Uncertainty radius is calibrated only from nested predictions in non-held-out years. Peak classification uses non-held-out-year peak climatology.'};
console.log(JSON.stringify(report,null,2));fs.mkdirSync(new URL('../artifacts/',import.meta.url),{recursive:true});fs.writeFileSync(new URL('../artifacts/model-benchmark.json',import.meta.url),JSON.stringify(report,null,2)+'\n');
