import Link from 'next/link';
import type {Metadata} from 'next';
import counts from '@/data/crane-counts.json';
import type {CraneSurvey} from '@/lib/types';
import {dailyHistoricalClimatology} from '@/lib/models/dailyClimatology';
import {solarTimes} from '@/lib/astronomy/solar';
export const metadata:Metadata={title:'Best Time to See Sandhill Cranes in Nebraska: Dates, Dawn & Dusk',description:'Use historical Platte River migration timing plus sunrise and sunset planning guidance to choose when to see Nebraska Sandhill Cranes.',alternates:{canonical:'https://chrisizworski.com/national-tools/platte-crane-live/best-time-to-see-sandhill-cranes-nebraska'}};
const rows=counts as CraneSurvey[];
function t(iso:string|null){return iso?new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',hour:'numeric',minute:'2-digit'}).format(new Date(iso)):'—'}
export default function Page(){const now=new Date(),solar=solarTimes(now),clim=dailyHistoricalClimatology(rows);const top=[...clim].sort((a,b)=>b.peakWindowProbability-a.peakWindowProbability||b.median-a.median).slice(0,10);const window=[...top].sort((a,b)=>a.dayIndex-b.dayIndex);return <main id="main" className="shell" style={{padding:'42px 20px 70px'}}><p className="eyebrow">TRIP TIMING</p><h1>Best time to see Sandhill Cranes in Nebraska</h1><section className="panel status-banner"><h2>Think in two time scales</h2><p><b>Season:</b> large abundance historically clusters in March, but timing varies materially by year. <b>Day:</b> dawn and dusk are generally the key river-roost viewing windows; daytime is better for feeding and movement away from the roost.</p></section><div className="grid" style={{marginTop:16}}><section className="panel span8"><p className="eyebrow">HISTORICAL PEAK-QUALITY WINDOW</p><h2>{window[0]?.dateKey??'—'} through {window.at(-1)?.dateKey??'—'}</h2><p>This range is derived from the days with the highest historical probability of abundance being at least 85% of each season’s modeled maximum. It is a climatology, not a promise for a future date.</p><div className="metric-row">{window.slice(0,4).map(d=><div className="metric" key={d.dateKey}><strong>{d.dateKey}</strong><div>{d.peakWindowProbability}% historical peak-quality probability</div><div className="fine">Median index {Math.round(d.median/1000)}k</div></div>)}</div></section><section className="panel span4"><p className="eyebrow">TODAY · CENTRAL TIME</p><h2>Light windows</h2><p><b>Sunrise:</b> {t(solar.sunrise)}<br/><b>Sunset:</b> {t(solar.sunset)}<br/><b>Civil dusk:</b> {t(solar.civilDusk)}</p><p className="fine">General planning: public dawn sites often warrant arrival 30–45 minutes before sunrise; dusk sites 45–60 minutes before sunset. Follow each site’s rules.</p></section><section className="panel span12"><h2>Dawn, daytime, or dusk?</h2><div className="site-list"><article className="site-card"><h3>Dawn</h3><p>Watch cranes leave river roosts as morning light develops. Arrive early and stay in designated areas.</p></article><article className="site-card"><h3>Daytime</h3><p>Look for feeding flocks and northbound movement from public roads and designated areas without approaching birds.</p></article><article className="site-card"><h3>Dusk</h3><p>Watch cranes return toward the Platte. Weather, river conditions, and disturbance can shift where birds settle.</p></article></div></section></div><p><Link href="/">Open current migration dashboard</Link> · <Link href="/platte-river-crane-viewing-map">Public viewing map</Link></p></main>}
